server:
  port: "8080"

database:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "771009"
  dbname: "task_manager"

jwt:
  secret: "20030222"
  expire_hours: 24

log:
  level: "debug"
  format: "console"
